
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1056925
	#The name of the modpack
	modpackName = "Homegrown: Sunlit Valley"
	#The version of the modpack
	modpackVersion = "4.0.7"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

